---
# Укажем hostname
- name: changing hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  register: "hostname_status"
  when: ansible_hostname != inventory_hostname_short

# Формируем файл /etc/hosts, выходной файл:
- name: generate file hosts
  template:
    src=hosts.j2
    dest=/etc/hosts

# Укажем timezone
# timedatectl list-timezones | grep Vl

- name: set timezone
  timezone:
    name: Asia/Vladivostok
